import { dobbyImages } from "./dobby";
import { jacquardImages } from "./jacquard";
import { velourImages } from "./velour";
import { waffleImages } from "./waffle";

const dobbySize = ["33x33cm", "50x90cm", "70x140cm", "100x180cm"];
const waffleSize = ["33x50cm", "40x70cm", "50x90cm", "70x140cm", "100x150cm"];
const type = "100% Cotton";
const color = [
	{ name: "White", color: "#fcfcfc" },
	{ name: "Blue", color: "#005689" },
	{ name: "Brown", color: "#854836" },
	{ name: "Grey", color: "#8f8787" },
	{ name: "Green", color: "#4c9173" },
	{ name: "Purple", color: "#8971d0" },
	{ name: "Pink", color: " #ffc1c8" },
];

export const terryTowelData = [
	{
		img: dobbyImages.images1[0].original,
		title: "Dobby Towels",
		dobbyData: [
			{
				id: "1",
				img: dobbyImages.images1[0].original,
				title: "Armul",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images1,
			},
			{
				id: "2",
				img: dobbyImages.images2[0].original,
				title: "Butterfly",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images2,
			},
			{
				id: "3",
				img: dobbyImages.images3[0].original,
				title: "Crown",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images3,
			},
			{
				id: "4",
				img: dobbyImages.images4[0].original,
				title: "Dresden",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images4,
			},
			{
				id: "5",
				img: dobbyImages.images5[0].original,
				title: "Gold Line",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images5,
			},
			{
				id: "6",
				img: dobbyImages.images6[0].original,
				title: "Lazanna",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images6,
			},
			{
				id: "7",
				img: dobbyImages.images7[0].original,
				title: "Velour Border",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images7,
			},
			{
				id: "8",
				img: dobbyImages.images8[0].original,
				title: "Waffle Border",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images8,
			},
			{
				id: "9",
				img: dobbyImages.images9[0].original,
				title: "Silver Line",
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images9,
			},
		],
	},
	{
		img: jacquardImages.images1[0].original,
		title: "Jacquard towels",
		data: [
			{
				id: "1",
				img: jacquardImages.images1[0].original,
				title: "Bella",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images1,
			},
			{
				id: "2",
				img: jacquardImages.images2[0].original,
				title: "Bondi",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images2,
			},
			{
				id: "3",
				img: jacquardImages.images3[0].original,
				title: "Chanel",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images3,
			},
			{
				id: "4",
				img: jacquardImages.images4[0].original,
				title: "DNK",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images4,
			},
			{
				id: "5",
				img: jacquardImages.images5[0].original,
				title: "Elligia",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images5,
			},
			{
				id: "6",
				img: jacquardImages.images6[0].original,
				title: "Lona",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images6,
			},
			{
				id: "7",
				img: jacquardImages.images7[0].original,
				title: "Nelly",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images7,
			},
			{
				id: "8",
				img: jacquardImages.images8[0].original,
				title: "Ronesans",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images8,
			},
			{
				id: "9",
				img: jacquardImages.images9[0].original,
				title: "Safia",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images9,
			},
			{
				id: "10",
				img: jacquardImages.images10[0].original,
				title: "Sakura",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images10,
			},
			{
				id: "11",
				img: jacquardImages.images11[0].original,
				title: "Zefir",
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images11,
			},
		],
	},
	{
		img: waffleImages.images1[0].original,
		title: "Waffle Towels",
		waffleData: [
			{
				id: "1",
				img: waffleImages.images1[0].original,
				title: "Flower",
				size: waffleSize,
				type,
				color,
				images: waffleImages.images1,
			},
			{
				id: "2",
				img: waffleImages.images2[0].original,
				title: "Waffle № 4",
				size: waffleSize,
				type,
				color,
				images: waffleImages.images2,
			},
			{
				id: "3",
				img: waffleImages.images3[0].original,
				title: "Uzor",
				size: waffleSize,
				type,
				color,
				images: waffleImages.images3,
			},
			{
				id: "4",
				img: waffleImages.images4[0].original,
				title: "Waffle",
				size: waffleSize,
				type,
				color,
				images: waffleImages.images4,
			},
		],
	},
	{
		img: velourImages.images1[0].original,
		title: "Velour Towels",
		velourData: [
			{
				id: "1",
				img: velourImages.images1[0].original,
				title: "Hermes",
				size: dobbySize,
				type,
				color,
				images: velourImages.images1,
			},
			{
				id: "2",
				img: velourImages.images2[0].original,
				title: "Wire",
				size: dobbySize,
				type,
				color,
				images: velourImages.images2,
			},
		],
	},
];
