import { dobbyImages } from "./dobby";
import { inceptionImages } from "./inception";
import { jacquardImages } from "./jacquard";
import { dobbySubtitle } from "./subtitle/dobby";
import { inceptionSubtitle } from "./subtitle/inception";
import { jacquardSubtitle } from "./subtitle/jacquard";
import { velourSubtitle } from "./subtitle/velour";
import { waffleSubtitle } from "./subtitle/waffle";
import { velourImages } from "./velour";
import { waffleImages } from "./waffle";

const dobbySize = ["33x33cm", "50x90cm", "70x140cm", "100x180cm"];
const waffleSize = ["33x50cm", "40x70cm", "50x90cm", "70x140cm", "100x150cm"];
const inceptionSize = ["50x90", "70x140cm", "100x180cm"];
const type = "100% Cotton";
const color = [
	{ name: "White", color: "#fcfcfc" },
	{ name: "Blue", color: "#005689" },
	{ name: "Brown", color: "#854836" },
	{ name: "Grey", color: "#8f8787" },
	{ name: "Green", color: "#4c9173" },
	{ name: "Purple", color: "#8971d0" },
	{ name: "Pink", color: " #ffc1c8" },
];
// White, Dark Grey, Light Grey, Blue
const inceptionColor = [
	{ name: "White", color: "#fcfcfc" },
	{ name: "Blue", color: "#005689" },
	{ name: "Light Grey", color: "#F5F5F5" },
	{ name: "Dark Grey", color: "#A9A9A9" },
];

export const terryTowelData = [
	{
		img: inceptionImages.images1[0].original,
		title: "Inception Towels",
		subtitle: inceptionSubtitle.inception1,
		inceptionData: [
			{
				id: "1",
				img: inceptionImages.images1[0].original,
				title: "Inception",
				subtitle: inceptionSubtitle.inception1,
				size: [inceptionSize[0]],
				type,
				color: inceptionColor,
				images: inceptionImages.images1,
			},
			{
				id: "2",
				img: inceptionImages.images2[0].original,
				title: "Inception",
				subtitle: inceptionSubtitle.inception2,
				size: [inceptionSize[1]],
				type,
				color: inceptionColor,
				images: inceptionImages.images2,
			},
			{
				id: "3",
				img: inceptionImages.images3[0].original,
				title: "Inception",
				subtitle: inceptionSubtitle.inception3,
				size: [inceptionSize[2]],
				type,
				color: inceptionColor,
				images: inceptionImages.images3,
			},
			{
				id: "4",
				img: inceptionImages.images4[0].original,
				title: "Inception",
				subtitle: inceptionSubtitle.inception4,
				size: [inceptionSize[0]],
				type,
				color: inceptionColor,
				images: inceptionImages.images4,
			},
			{
				id: "5",
				img: inceptionImages.images5[0].original,
				title: "Inception",
				subtitle: inceptionSubtitle.inception5,
				size: [inceptionSize[1]],
				type,
				color: inceptionColor,
				images: inceptionImages.images5,
			},
			{
				id: "6",
				img: inceptionImages.images6[0].original,
				title: "Inception",
				subtitle: inceptionSubtitle.inception6,
				size: [inceptionSize[2]],
				type,
				color: inceptionColor,
				images: inceptionImages.images6,
			},
		],
	},
	{
		img: dobbyImages.images1[0].original,
		title: "Dobby Towels",
		subtitle: dobbySubtitle.armul,
		dobbyData: [
			{
				id: "1",
				img: dobbyImages.images1[0].original,
				title: "Armul",
				subtitle: dobbySubtitle.armul,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images1,
			},
			{
				id: "2",
				img: dobbyImages.images2[0].original,
				title: "Butterfly",
				subtitle: dobbySubtitle.butterfly,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images2,
			},
			{
				id: "3",
				img: dobbyImages.images3[0].original,
				title: "Crown",
				subtitle: dobbySubtitle.crown,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images3,
			},
			{
				id: "4",
				img: dobbyImages.images4[0].original,
				title: "Dresden",
				subtitle: dobbySubtitle.dresden,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images4,
			},
			{
				id: "5",
				img: dobbyImages.images5[0].original,
				title: "Gold Line",
				subtitle: dobbySubtitle.gold_line,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images5,
			},
			{
				id: "6",
				img: dobbyImages.images6[0].original,
				title: "Lazanna",
				subtitle: dobbySubtitle.lazanna,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images6,
			},
			{
				id: "7",
				img: dobbyImages.images7[0].original,
				title: "Velour Border",
				subtitle: dobbySubtitle.velour,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images7,
			},
			{
				id: "8",
				img: dobbyImages.images8[0].original,
				title: "Waffle Border",
				subtitle: dobbySubtitle.waffle,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images8,
			},
			{
				id: "9",
				img: dobbyImages.images9[0].original,
				title: "Silver Line",
				subtitle: dobbySubtitle.silver,
				size: dobbySize,
				type,
				color,
				images: dobbyImages.images9,
			},
		],
	},
	{
		img: jacquardImages.images1[0].original,
		title: "Jacquard towels",
		subtitle: jacquardSubtitle.nelly,
		data: [
			{
				id: "1",
				img: jacquardImages.images1[0].original,
				title: "Nelly",
				subtitle: jacquardSubtitle.nelly,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images1,
			},
			{
				id: "2",
				img: jacquardImages.images2[0].original,
				title: "Bella",
				subtitle: jacquardSubtitle.bella,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images2,
			},
			{
				id: "3",
				img: jacquardImages.images3[0].original,
				title: "Bondi",
				subtitle: jacquardSubtitle.bondi,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images3,
			},
			{
				id: "4",
				img: jacquardImages.images4[0].original,
				title: "Chanel",
				subtitle: jacquardSubtitle.chanel,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images4,
			},
			{
				id: "5",
				img: jacquardImages.images5[0].original,
				title: "DNK",
				subtitle: jacquardSubtitle.dnk,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images5,
			},
			{
				id: "6",
				img: jacquardImages.images6[0].original,
				title: "Ellegia",
				subtitle: jacquardSubtitle.ellegia,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images6,
			},
			{
				id: "7",
				img: jacquardImages.images7[0].original,
				title: "Lona",
				subtitle: jacquardSubtitle.lona,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images7,
			},
			{
				id: "8",
				img: jacquardImages.images8[0].original,
				title: "Ronesans",
				subtitle: jacquardSubtitle.ronesans,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images8,
			},
			{
				id: "9",
				img: jacquardImages.images9[0].original,
				title: "Safia",
				subtitle: jacquardSubtitle.safia,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images9,
			},
			{
				id: "10",
				img: jacquardImages.images10[0].original,
				title: "Sakura",
				subtitle: jacquardSubtitle.sakura,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images10,
			},
			{
				id: "11",
				img: jacquardImages.images11[0].original,
				title: "Zefir",
				subtitle: jacquardSubtitle.zafir,
				size: dobbySize,
				type,
				color,
				images: jacquardImages.images11,
			},
		],
	},
	{
		img: waffleImages.images1[0].original,
		title: "Waffle Towels",
		subtitle: waffleSubtitle.waffle_No_4,
		waffleData: [
			{
				id: "1",
				img: waffleImages.images1[0].original,
				title: "Waffle № 4",
				subtitle: waffleSubtitle.waffle_No_4,
				size: waffleSize,
				type,
				color,
				images: waffleImages.images1,
			},
			{
				id: "2",
				img: waffleImages.images2[0].original,
				title: "Waffle № 3",
				subtitle: waffleSubtitle.waffle_No_3,
				size: waffleSize,
				type,
				color,
				images: waffleImages.images2,
			},
			{
				id: "3",
				img: waffleImages.images3[0].original,
				title: "Uzor",
				subtitle: waffleSubtitle.uzor,
				size: waffleSize,
				type,
				color,
				images: waffleImages.images3,
			},
			{
				id: "4",
				img: waffleImages.images4[0].original,
				title: "Flower",
				subtitle: waffleSubtitle.flower,
				size: waffleSize,
				type,
				color,
				images: waffleImages.images4,
			},
		],
	},
	{
		img: velourImages.images1[0].original,
		title: "Velour Towels",
		subtitle: velourSubtitle.wire,
		velourData: [
			{
				id: "1",
				img: velourImages.images1[0].original,
				title: "Wire",
				subtitle: velourSubtitle.wire,
				size: dobbySize,
				type,
				color,
				images: velourImages.images1,
			},
			{
				id: "2",
				img: velourImages.images2[0].original,
				title: "Hermes",
				subtitle: velourSubtitle.hermes,
				size: dobbySize,
				type,
				color,
				images: velourImages.images2,
			},
		],
	},
];
