import Head from "next/head";
import { Inter } from "@next/font/google";
import Layout from "@/components/layout.js";
import About from "@/components/sections/about";
import Featured from "@/components/sections/featured";
import Towels from "@/components/sections/towels";
import Beddings from "@/components/sections/beddings";
import Threads from "@/components/sections/threads";
import Cloth from "@/components/sections/cloth";
import Partners from "@/components/sections/partners";
import Reviews from "@/components/sections/reviews";
import Contacts from "@/components/sections/contacts";

console.log("hello from index js");

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Big Way Trading</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BigWayTrading_Logo_bk.png" />
      </Head>
      <main>
        <Layout>
          <About />
          <Featured />
          <Towels />
          <Beddings />
          <Threads />
          <Cloth />
          <Partners />
          <Reviews />
          <Contacts />
        </Layout>
      </main>
    </>
  );
}
